title: Try Auth Docs
description: Try Auth documentation!
theme: just-the-docs

url: https://tryauth.github.io/docs

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
